// Банк заданий Mission Control — Grade 3–4 (Common Core ELA), тема: космос
const SKILLS = [
  {id:'s3', name:'Хвостик -s', full:'He / She / It + глагол с -s', icon:'🛰️'},
  {id:'past', name:'Прошедшее время', full:'Неправильные глаголы: go → went', icon:'🌑'},
  {id:'cont', name:'Прямо сейчас', full:'am / is / are + глагол-ing', icon:'🚀'},
  {id:'prep', name:'Где что', full:'in, on, at, under, between, above', icon:'🧭'},
  {id:'plur', name:'Много', full:'Множественное число, в т.ч. хитрое', icon:'✨'},
  {id:'comp', name:'Сравнение', full:'bigger, hotter, more beautiful … than', icon:'⚖️'},
  {id:'art', name:'a / an / the', full:'Артикли', icon:'🔭'},
  {id:'read', name:'Чтение', full:'Понять текст и ответить', icon:'📡'},
  {id:'voc', name:'Словарь', full:'Космические слова', icon:'👨‍🚀'}
];

const PLANETS = {
  s3:{n:'Mercury', f:'Mercury is the smallest planet. It moves around the Sun faster than any other planet — one year there lasts only 88 days.'},
  past:{n:'Venus', f:'Venus spins backwards. If you stood there, the Sun would rise in the west and set in the east.'},
  cont:{n:'Mars', f:'Right now robots are driving on Mars. Perseverance is looking for signs of ancient life in an old river delta.'},
  prep:{n:'Jupiter', f:'A giant storm called the Great Red Spot has been turning on Jupiter for more than 300 years. Earth could fit inside it.'},
  plur:{n:'Saturn', f:'Saturn has 274 moons — more than any other planet. Its rings are made of billions of pieces of ice.'},
  comp:{n:'Uranus', f:'Uranus is colder than Neptune, even though it sits closer to the Sun. It rolls on its side like a barrel.'},
  art:{n:'Neptune', f:'The winds on Neptune are the fastest in the Solar System — up to 2,000 km per hour.'},
  read:{n:'Pluto', f:'Pluto has a huge heart-shaped glacier of frozen nitrogen. We only saw it clearly in 2015.'},
  voc:{n:'Deep Space', f:'The nearest star after the Sun is Proxima Centauri. Light from it travels 4 years to reach your eyes.'}
};

// q — вопрос, o — варианты (первый всегда верный, перемешиваются), fix — верный ответ текстом
// why — разбор ошибки, rule — правило, ex — пример, again — объяснение с другой стороны
// up — мини-проверка после объяснения {q, a}
const BANK = {
s3:[
 {q:'He ___ to the space station every morning.', o:['goes','go','going','gone'],
  why:'«He» — это один человек. У глагола рядом с he / she / it вырастает хвостик -s.',
  rule:'he / she / it + глагол + s', ex:'She flies. It works. He goes.',
  again:'Проверь себя так: если можешь заменить слово на «он / она / оно» — ставь -s.',
  up:{q:'She ___ (fly) the shuttle.', a:'flies'}},
 {q:'The rover ___ pictures of Mars.', o:['takes','take','taking','took'],
  why:'«The rover» — один марсоход. Значит it. А к it глагол идёт с -s.',
  rule:'один предмет = it = глагол с -s', ex:'The engine starts. The robot moves.',
  again:'Один — с хвостиком. Много — без хвостика: The rovers take.',
  up:{q:'The engine ___ (start).', a:'starts'}},
 {q:'My brother and I ___ the stars at night.', o:['watch','watches','watching','watched'],
  why:'«My brother and I» — это уже двое, we. К we хвостик не нужен.',
  rule:'I / you / we / they — глагол без -s', ex:'We watch. They fly. I look.',
  again:'Хвостик -s достаётся только одному: he, she, it. Остальные обходятся без него.',
  up:{q:'They ___ (work) at NASA.', a:'work'}},
 {q:'Anna ___ about becoming an astronaut.', o:['dreams','dream','dreaming','dreamt'],
  why:'Anna — одна девочка, то есть she. Значит dreams.',
  rule:'имя одного человека = he/she = глагол с -s', ex:'Anna dreams. Tom reads.',
  again:'Подставь вместо имени «она» — сразу слышно, что нужен хвостик.',
  up:{q:'Tom ___ (read) a book about planets.', a:'reads'}},
 {q:'It ___ very cold on Mars at night.', o:['gets','get','getting','got'],
  why:'It — прямой сигнал: ставим -s.',
  rule:'it + глагол + s', ex:'It gets. It rains. It works.',
  again:'It всегда один. Один — значит с хвостиком.',
  up:{q:'It ___ (rain) on Titan, but with methane.', a:'rains'}},
 {q:'Astronauts ___ special suits in space.', o:['wear','wears','wearing','wore'],
  why:'Astronauts — их много, they. Хвостик не нужен.',
  rule:'много кого-то = they = без -s', ex:'Astronauts wear. Scientists study.',
  again:'Смотри на конец слова: astronautS — уже есть -s у существительного, значит глаголу он не нужен.',
  up:{q:'Scientists ___ (study) the Moon.', a:'study'}},
 {q:'The Sun ___ light to all the planets.', o:['gives','give','giving','gave'],
  why:'Солнце одно. Один предмет = it = gives.',
  rule:'один = -s', ex:'The Sun gives. The Moon shines.',
  again:'Сколько Солнц? Одно. Значит хвостик обязателен.',
  up:{q:'The Moon ___ (shine) at night.', a:'shines'}},
 {q:'Does the telescope ___ well?', o:['work','works','working','worked'],
  why:'Хитрость: если рядом есть does, хвостик -s уже забрал себе does. Глагол остаётся голым.',
  rule:'does + глагол без -s', ex:'Does it work? Does she fly?',
  again:'Хвостик -s в предложении только один. Он ушёл в does — значит глаголу не достанется.',
  up:{q:'Does he ___ (want) to go?', a:'want'}}
],
past:[
 {q:'Yuri Gagarin ___ into space in 1961.', o:['went','goed','go','gone'],
  why:'go — неправильный глагол. Он не берёт -ed, а меняется целиком: go → went.',
  rule:'go → went', ex:'He went home. She went to school.',
  again:'Неправильные глаголы просто запоминают. goed не бывает никогда.',
  up:{q:'They ___ (go) to the launch site.', a:'went'}},
 {q:'The astronaut ___ a photo of the Earth.', o:['took','taked','take','taken'],
  why:'take → took. Это неправильный глагол, -ed к нему не приклеивается.',
  rule:'take → took', ex:'I took a book. He took a picture.',
  again:'taked не существует. Слово меняет середину: a → oo.',
  up:{q:'She ___ (take) the camera.', a:'took'}},
 {q:'We ___ the stars through a telescope last night.', o:['saw','seen','see','sawed'],
  why:'see → saw. А seen — другая форма, она живёт только с have/has.',
  rule:'see → saw', ex:'I saw a comet. We saw Mars.',
  again:'Простое прошедшее — saw. Seen без have не ходит.',
  up:{q:'He ___ (see) the rocket.', a:'saw'}},
 {q:'The rocket ___ up into the sky.', o:['flew','flied','fly','flown'],
  why:'fly → flew. Ещё один неправильный.',
  rule:'fly → flew', ex:'The bird flew. The plane flew.',
  again:'flied не бывает. Меняется гласная: y → ew.',
  up:{q:'The birds ___ (fly) away.', a:'flew'}},
 {q:'She ___ a book about black holes.', o:['read','readed','reads','reading'],
  why:'read → read. Пишется одинаково, но читается по-разному: [рид] → [ред].',
  rule:'read → read (звучит «ред»)', ex:'I read it yesterday.',
  again:'Форма та же, меняется только звук. Это единственная такая шутка в английском.',
  up:{q:'They ___ (read) the report yesterday.', a:'read'}},
 {q:'The crew ___ breakfast before the launch.', o:['had','haved','has','having'],
  why:'have → had.',
  rule:'have / has → had', ex:'She had a plan. We had lunch.',
  again:'В прошедшем времени и have, и has превращаются в одно слово — had.',
  up:{q:'He ___ (have) a question.', a:'had'}},
 {q:'They ___ the rover to Mars in 2020.', o:['sent','sended','send','sending'],
  why:'send → sent. Конец меняется на -t.',
  rule:'send → sent', ex:'I sent a letter.',
  again:'Целая семья так делает: send → sent, build → built, spend → spent.',
  up:{q:'She ___ (send) a message.', a:'sent'}},
 {q:'The engineers ___ a new spacecraft.', o:['built','builded','build','building'],
  why:'build → built.',
  rule:'build → built', ex:'They built a house.',
  again:'Та же семья, что send → sent. Конец -d меняется на -t.',
  up:{q:'We ___ (build) a model rocket.', a:'built'}}
],
cont:[
 {q:'Look! The rocket ___ off right now.', o:['is taking','takes','take','took'],
  why:'«Прямо сейчас» — значит нужна пара: is / am / are + глагол с -ing.',
  rule:'am / is / are + ing = происходит сейчас', ex:'He is running. They are working.',
  again:'Сигнальные слова: now, right now, look!, at the moment. Увидел их — ставь -ing.',
  up:{q:'Look! She ___ (run).', a:'is running'}},
 {q:'The astronauts ___ an experiment at the moment.', o:['are doing','is doing','do','does'],
  why:'Astronauts — их много, значит are, а не is.',
  rule:'I am / he-she-it is / we-you-they are', ex:'They are doing. He is doing.',
  again:'Сначала выбери помощника по количеству, потом уже прилепляй -ing.',
  up:{q:'The engineers ___ (check) the engine.', a:'are checking'}},
 {q:'I ___ a picture of the Moon now.', o:['am drawing','is drawing','are drawing','draw'],
  why:'С I всегда идёт am. Только с ним.',
  rule:'I + am', ex:'I am reading. I am flying.',
  again:'am — личный помощник слова I. Больше он ни к кому не ходит.',
  up:{q:'I ___ (write) a letter.', a:'am writing'}},
 {q:'She ___ her spacesuit right now.', o:['is putting on','puts on','are putting on','put on'],
  why:'She — один человек, значит is. Плюс -ing, потому что сейчас.',
  rule:'she + is + ing', ex:'She is eating. She is working.',
  again:'Два шага: кто (she → is) и когда (сейчас → ing).',
  up:{q:'He ___ (open) the hatch.', a:'is opening'}},
 {q:'We ___ to the countdown at the moment.', o:['are listening','is listening','listen','listened'],
  why:'We — нас много, значит are listening.',
  rule:'we + are + ing', ex:'We are watching. We are waiting.',
  again:'We, you, they — все трое берут are.',
  up:{q:'They ___ (wait) for the signal.', a:'are waiting'}},
 {q:'Every day the station ___ around the Earth 16 times.', o:['goes','is going','go','going'],
  why:'Ловушка: «every day» — это не «сейчас», а привычка. Тут -ing не нужен.',
  rule:'every day / usually / always = обычное время, без ing', ex:'He goes every day. She works on Mondays.',
  again:'Сравни: Now it is going (сейчас) — Every day it goes (всегда).',
  up:{q:'She ___ (work) at NASA every day.', a:'works'}},
 {q:'What ___ you ___ ?', o:['are / doing','is / doing','do / doing','are / do'],
  why:'В вопросе помощник (are) выходит вперёд, а -ing остаётся у глагола.',
  rule:'What are you doing?', ex:'Where is he going? What are they eating?',
  again:'Порядок: вопросное слово → are/is/am → кто → глагол+ing.',
  up:{q:'Where ___ he ___ (go)?', a:'is going'}},
 {q:'The Sun ___ brightly today.', o:['is shining','shines bright','are shining','shine'],
  why:'Today + описание момента = is shining. И это один Sun, значит is.',
  rule:'один предмет + is + ing', ex:'The star is shining.',
  again:'Сколько Солнц — одно, значит is. Когда — сейчас, значит shining.',
  up:{q:'The engine ___ (make) a loud noise.', a:'is making'}}
],
prep:[
 {q:'The satellite is ___ the Earth.', o:['above','in','at','between'],
  why:'above — «над чем-то, выше». Спутник висит над планетой.',
  rule:'above = над', ex:'The lamp is above the table.',
  again:'above — сверху и не касаясь. on — сверху и касаясь.',
  up:{q:'The clouds are ___ (над) the mountain.', a:'above'}},
 {q:'We landed ___ the Moon.', o:['on','in','at','under'],
  why:'На поверхность чего-то садятся — on. On the Moon, on Mars, on Earth.',
  rule:'on + поверхность', ex:'on the table, on the floor, on Mars',
  again:'In — внутрь, on — на поверхность. На Луну садятся сверху, значит on.',
  up:{q:'The rover is ___ Mars.', a:'on'}},
 {q:'Mars is ___ Earth and Jupiter.', o:['between','among','in','on'],
  why:'between — между двумя. А among — среди многих.',
  rule:'between A and B = между двумя', ex:'between the Sun and Earth',
  again:'Двое — between. Толпа — among.',
  up:{q:'The Moon is ___ the Earth and the Sun during an eclipse.', a:'between'}},
 {q:'There is water ___ the ice on Europa.', o:['under','on','at','above'],
  why:'under — под чем-то. Океан спрятан под слоем льда.',
  rule:'under = под', ex:'The cat is under the chair.',
  again:'above — сверху, under — снизу. Пара-противоположность.',
  up:{q:'The book is ___ (под) the table.', a:'under'}},
 {q:'The astronaut is ___ the spacecraft.', o:['in','on','at','above'],
  why:'Внутри корабля — значит in.',
  rule:'in = внутри', ex:'in the box, in the room, in the car',
  again:'Можешь зайти внутрь — in. Стоишь сверху — on.',
  up:{q:'The samples are ___ the box.', a:'in'}},
 {q:'The launch is ___ 9 o\'clock.', o:['at','in','on','under'],
  why:'Точное время — at. At 9 o\'clock, at noon, at midnight.',
  rule:'at + точное время', ex:'at 5 o\'clock, at 7:30',
  again:'Лесенка времени: at — час, on — день, in — месяц и год.',
  up:{q:'The meeting is ___ 6 o\'clock.', a:'at'}},
 {q:'Gagarin flew into space ___ 1961.', o:['in','at','on','under'],
  why:'Год — это большой кусок времени, значит in.',
  rule:'in + год, месяц, век', ex:'in 2026, in April, in summer',
  again:'Та же лесенка: at (час) → on (день) → in (год).',
  up:{q:'The rover landed ___ 2021.', a:'in'}},
 {q:'The launch happened ___ Monday.', o:['on','in','at','above'],
  why:'День недели — on.',
  rule:'on + день', ex:'on Monday, on May 5th',
  again:'День — средняя ступенька лесенки: on.',
  up:{q:'We have a lesson ___ Friday.', a:'on'}}
],
plur:[
 {q:'There are many ___ in the Solar System.', o:['planets','planetes','planet','planetz'],
  why:'Обычное правило: просто добавляем -s.',
  rule:'+ s', ex:'star → stars, rocket → rockets',
  again:'Никаких лишних букв, только -s на конце.',
  up:{q:'one star → three ___', a:'stars'}},
 {q:'Astronauts study the ___ of other planets.', o:['skies','skys','sky','skyes'],
  why:'Если слово кончается на согласную + y, то y превращается в i и добавляется -es.',
  rule:'-y → -ies', ex:'city → cities, baby → babies',
  again:'Но если перед y стоит гласная — просто -s: day → days, boy → boys.',
  up:{q:'one city → many ___', a:'cities'}},
 {q:'The rover found two ___ of ice.', o:['pieces','piecies','piece','piecs'],
  why:'Тут перед -s ничего менять не надо: piece → pieces.',
  rule:'+ s', ex:'place → places, face → faces',
  again:'Слово уже кончается на -e, поэтому просто прибавь -s.',
  up:{q:'one place → two ___', a:'places'}},
 {q:'Space suits protect the ___ of astronauts.', o:['bodies','bodys','body','bodyes'],
  why:'body — согласная + y, значит bodies.',
  rule:'-y → -ies', ex:'story → stories, family → families',
  again:'Смотри на букву перед y. Согласная — меняем на ies.',
  up:{q:'one story → many ___', a:'stories'}},
 {q:'Scientists sent three ___ to Mars.', o:['probes','probies','probs','probe'],
  why:'Обычное -s.',
  rule:'+ s', ex:'tube → tubes, cube → cubes',
  again:'-ies бывает только у слов на согласную + y. Здесь не тот случай.',
  up:{q:'one tube → five ___', a:'tubes'}},
 {q:'The crew took photos of six ___ on Mars.', o:['rocks','rockes','rock','rocki'],
  why:'Просто -s.',
  rule:'+ s', ex:'book → books, desk → desks',
  again:'-es добавляют после s, x, ch, sh: boxes, watches. Тут просто k — значит -s.',
  up:{q:'one box → two ___', a:'boxes'}},
 {q:'Two ___ work on the station.', o:['men','mans','mens','man'],
  why:'man — особое слово. Меняется середина: a → e.',
  rule:'man → men, woman → women', ex:'one man, two men',
  again:'Такие слова просто запоминают. mans не бывает.',
  up:{q:'one woman → two ___', a:'women'}},
 {q:'The telescope showed us new ___ .', o:['galaxies','galaxys','galaxes','galaxy'],
  why:'galaxy — согласная + y, значит galaxies.',
  rule:'-y → -ies', ex:'sky → skies, galaxy → galaxies',
  again:'Отбрасываешь y, ставишь ies. Работает всегда, если перед y согласная.',
  up:{q:'one sky → many ___', a:'skies'}}
],
comp:[
 {q:'Jupiter is ___ than Earth.', o:['bigger','more big','biggest','big'],
  why:'Короткое слово получает -er. А more ставят только к длинным.',
  rule:'короткое слово + er + than', ex:'small → smaller, fast → faster',
  again:'Слово из одного слога? Тогда -er. more big не говорят никогда.',
  up:{q:'small → ___ than', a:'smaller'}},
 {q:'Venus is ___ than Mercury.', o:['hotter','hoter','more hot','hottest'],
  why:'Короткая гласная в середине — последняя буква удваивается: hot → hotter.',
  rule:'hot → hotter, big → bigger', ex:'sad → sadder, thin → thinner',
  again:'Одна гласная между двумя согласными — согласную на конце удваиваем.',
  up:{q:'big → ___', a:'bigger'}},
 {q:'A nebula is ___ than a planet.', o:['more beautiful','beautifuler','beautifullest','beautiful'],
  why:'Длинное слово (3 слога) — берём more, а не -er.',
  rule:'длинное слово: more + слово + than', ex:'more interesting, more difficult',
  again:'Попробуй сказать beautifuler вслух — язык не поворачивается. Поэтому more.',
  up:{q:'interesting → ___ than', a:'more interesting'}},
 {q:'This telescope is ___ than that one.', o:['better','gooder','more good','best'],
  why:'good — исключение. good → better → the best.',
  rule:'good → better', ex:'bad → worse, far → further',
  again:'Три исключения выучить и забыть: good→better, bad→worse, far→further.',
  up:{q:'bad → ___', a:'worse'}},
 {q:'The Sun is the ___ object in the Solar System.', o:['largest','larger','most large','large'],
  why:'«Самый» — это the + слово с -est.',
  rule:'the + слово + est = самый', ex:'the biggest, the fastest',
  again:'-er сравнивает двоих. -est выбирает одного из всех. И перед ним всегда the.',
  up:{q:'fast → the ___', a:'fastest'}},
 {q:'Neptune is ___ from the Sun than Uranus.', o:['farther','farer','more far','farthest'],
  why:'far → farther. Ещё одно исключение.',
  rule:'far → farther / further', ex:'Mars is farther than Venus.',
  again:'farer не бывает. Запомни как отдельное слово.',
  up:{q:'far → ___ than', a:'farther'}},
 {q:'A comet moves ___ than a planet.', o:['faster','more fast','fastest','fast'],
  why:'fast — короткое слово, значит faster.',
  rule:'+ er + than', ex:'slow → slower, high → higher',
  again:'Один слог — всегда -er, без more.',
  up:{q:'slow → ___ than', a:'slower'}},
 {q:'Pluto is ___ than Mercury.', o:['smaller','more small','smallest','small'],
  why:'small короткое, значит smaller. И после сравнения обязательно than.',
  rule:'smaller than', ex:'colder than, longer than',
  again:'Пара всегда вместе: -er … than.',
  up:{q:'cold → ___ than', a:'colder'}}
],
art:[
 {q:'I saw ___ astronaut on TV yesterday.', o:['an','a','the','—'],
  why:'Слово начинается с гласного звука (a-stronaut), значит an.',
  rule:'an перед гласным звуком: a, e, i, o, u', ex:'an apple, an engineer, an orbit',
  again:'Скажи вслух «a astronaut» — две гласные подряд спотыкаются. Поэтому an.',
  up:{q:'___ engineer', a:'an'}},
 {q:'She wants to be ___ scientist.', o:['a','an','the','—'],
  why:'scientist начинается с согласного звука [s], значит a.',
  rule:'a перед согласным звуком', ex:'a rocket, a star, a book',
  again:'Смотри не на букву, а на звук в начале слова.',
  up:{q:'___ rocket', a:'a'}},
 {q:'___ Sun is a star.', o:['The','A','An','—'],
  why:'Солнце одно на всех — такое единственное всегда берёт the.',
  rule:'the — когда предмет один-единственный', ex:'the Moon, the Earth, the sky',
  again:'A — «какой-то один из многих». The — «тот самый, единственный».',
  up:{q:'___ Moon is bright tonight.', a:'The'}},
 {q:'I read ___ book about Mars. ___ book was great.', o:['a / The','the / A','an / The','a / A'],
  why:'Первый раз — a (какая-то книга). Второй раз — the, потому что уже знакомая.',
  rule:'впервые — a, повторно — the', ex:'I saw a cat. The cat was black.',
  again:'A знакомит, the вспоминает.',
  up:{q:'I have a dog. ___ dog is small.', a:'The'}},
 {q:'It takes ___ hour to get there.', o:['an','a','the','—'],
  why:'В слове hour буква h не читается — начинается со звука [au]. Значит an.',
  rule:'решает звук, а не буква', ex:'an hour, an honest man',
  again:'Буква согласная, а звук гласный. Английский слушает звук.',
  up:{q:'___ honest answer', a:'an'}},
 {q:'Mars is ___ fourth planet from the Sun.', o:['the','a','an','—'],
  why:'Порядковые числа (первый, второй, четвёртый) всегда идут с the.',
  rule:'the + first / second / fourth', ex:'the first day, the third rocket',
  again:'Четвёртая планета только одна — значит the.',
  up:{q:'___ first astronaut', a:'the'}},
 {q:'Astronauts need ___ oxygen to breathe.', o:['—','a','an','the'],
  why:'Oxygen нельзя посчитать (не бывает «два кислорода»), поэтому артикль не нужен.',
  rule:'у неисчисляемых слов артикля нет', ex:'water, air, sand, music',
  again:'Можешь сказать «два таких»? Нет — значит без артикля.',
  up:{q:'We need ___ water. (артикль или прочерк?)', a:'—'}},
 {q:'This is ___ interesting experiment.', o:['an','a','the','—'],
  why:'interesting начинается с гласного звука [i], значит an.',
  rule:'an + гласный звук', ex:'an interesting book, an old rocket',
  again:'Артикль смотрит на следующее слово — тут это interesting.',
  up:{q:'___ old telescope', a:'an'}}
],
read:[
 {q:'"The Perseverance rover landed in Jezero Crater in 2021. Long ago, a river flowed into this crater and made a lake. Scientists hope the rover will find signs of ancient life in the old mud."\n\nWhy did scientists choose Jezero Crater?',
  o:['Because a river and a lake were once there','Because it is the biggest crater on Mars','Because the rover landed there in 2021','Because there is water there now'],
  why:'Ответ спрятан во втором предложении: когда-то там была река и озеро. Где была вода — там могла быть жизнь.',
  rule:'Ищи в тексте предложение, которое отвечает именно на вопрос «почему»',
  ex:'Слова-подсказки: because, so, that is why',
  again:'Вариант «rover landed there in 2021» — это факт из текста, но он отвечает на «когда», а не на «почему».',
  up:{q:'Что искал ровер? (одно слово из текста)', a:'life'}},
 {q:'"A black hole is not really a hole. It is a place where gravity pulls so hard that nothing can escape — not even light. That is why we cannot see a black hole. We only see how it pulls stars and gas around it."\n\nWhy can\'t we see a black hole?',
  o:['Because light cannot escape from it','Because it is very far away','Because it is a hole in space','Because it has no stars around it'],
  why:'Текст говорит прямо: свет не может вырваться. Нет света — нечего увидеть.',
  rule:'Фраза «That is why» всегда указывает на ответ, стоящий прямо перед ней',
  ex:'It rained. That is why we stayed home.',
  again:'«Far away» в тексте вообще не упоминается — значит это не ответ.',
  up:{q:'Что чёрная дыра не отпускает наружу?', a:'light'}},
 {q:'"On the ISS astronauts sleep in sleeping bags fixed to the wall. If they did not do this, they would float around the station and bump into things while sleeping."\n\nWhy are the sleeping bags fixed to the wall?',
  o:['So astronauts do not float around while sleeping','Because there are no beds on the station','Because the wall is warmer','So astronauts can see the Earth'],
  why:'Второе предложение объясняет: без крепления они летали бы по станции.',
  rule:'«If they did not …, they would …» — это объяснение причины',
  ex:'If I did not set an alarm, I would be late.',
  again:'Текст не говорит ни про кровати, ни про тепло. Отвечай только тем, что написано.',
  up:{q:'Где астронавты спят? (два слова)', a:'sleeping bags'}},
 {q:'"Saturn\'s rings look solid from far away. But they are made of billions of pieces of ice and rock. Some pieces are as small as a grain of sand. Others are as big as a house."\n\nWhat are Saturn\'s rings made of?',
  o:['Pieces of ice and rock','One solid piece of ice','Sand from Saturn','Gas and dust'],
  why:'Второе предложение отвечает дословно: billions of pieces of ice and rock.',
  rule:'На вопрос «what … made of» ищи слова made of в тексте',
  ex:'The house is made of wood.',
  again:'«Solid» в тексте есть, но с оговоркой: look solid — только выглядят такими.',
  up:{q:'Какого размера самые мелкие кусочки? (сравнение из текста)', a:'a grain of sand'}},
 {q:'"The Moon has no air. Because of this, sound cannot travel there. If you shouted on the Moon, your friend standing next to you would hear nothing."\n\nWhat is the main idea of this text?',
  o:['There is no sound on the Moon because there is no air','The Moon is a dangerous place for people','Friends should not shout at each other','The Moon is very far from Earth'],
  why:'Главная мысль — то, о чём весь текст целиком, а не одна деталь. Здесь все три предложения про одно: нет воздуха — нет звука.',
  rule:'Главная мысль объединяет весь текст, а не пересказывает одну строчку',
  ex:'Проверь: подходит ли твой вариант ко ВСЕМ предложениям?',
  again:'«Dangerous place» звучит правдоподобно, но в тексте об этом ни слова.',
  up:{q:'Почему на Луне не слышно звука? (одно слово)', a:'air'}},
 {q:'"Comets come from the cold outer edge of the Solar System. When a comet flies near the Sun, its ice starts to melt. The gas and dust form a long bright tail that always points away from the Sun."\n\nWhen does a comet get its tail?',
  o:['When it flies near the Sun','When it is far from the Sun','When it hits a planet','When it is made of ice'],
  why:'Второе и третье предложения связаны: подлетает к Солнцу → лёд тает → появляется хвост.',
  rule:'Вопрос «when» — ищи слова when, after, before',
  ex:'When it rains, the street gets wet.',
  again:'Обрати внимание: хвост направлен ОТ Солнца, но появляется он БЛИЗКО к Солнцу. Это разные вещи.',
  up:{q:'Куда направлен хвост кометы — к Солнцу или от него?', a:'away'}},
 {q:'"Astronauts exercise two hours every day. In space, muscles and bones become weak because there is almost no gravity to work against. Exercise keeps the body strong for the return to Earth."\n\nWhy do astronauts exercise so much?',
  o:['Because muscles get weak without gravity','Because they have a lot of free time','Because exercise is fun in space','Because they want to grow taller'],
  why:'Причина названа прямо: без гравитации мышцы и кости слабеют.',
  rule:'Слово because — прямой указатель на причину',
  ex:'He stayed home because he was ill.',
  again:'Два часа в день — это сколько, а не почему. Вопрос был «почему».',
  up:{q:'Чего почти нет в космосе? (одно слово)', a:'gravity'}},
 {q:'"The James Webb telescope does not look at the sky in normal light. It sees infrared — a kind of light our eyes cannot catch. This lets it look through clouds of dust and see the very first stars."\n\nWhat can the telescope do that our eyes cannot?',
  o:['See infrared light through dust','Travel to other planets','Make the stars brighter','Take colour photos'],
  why:'Текст говорит: оно видит инфракрасный свет, который глаз не ловит, и потому смотрит сквозь пыль.',
  rule:'Сравнение «cannot» подсказывает, где спрятана разница',
  ex:'Dogs can hear sounds we cannot hear.',
  again:'Про путешествия и цветные фото в тексте нет ни слова.',
  up:{q:'Сквозь что телескоп может смотреть? (одно слово)', a:'dust'}}
],
voc:[
 {q:'A ___ is a machine that drives on the surface of a planet.', o:['rover','rocket','orbit','crater'],
  why:'rover — от слова «бродить». Это машина, которая ездит по планете.',
  rule:'rover = планетоход', ex:'The Curiosity rover drives on Mars.',
  again:'rocket летит, rover едет.',
  up:{q:'Как называется машина, которая ездит по Марсу?', a:'rover'}},
 {q:'A ___ is a big hole in the ground made by a falling rock.', o:['crater','planet','comet','moon'],
  why:'crater — воронка от удара метеорита.',
  rule:'crater = кратер', ex:'The Moon is covered with craters.',
  again:'Comet — это сам летящий объект. Crater — след, который он оставил.',
  up:{q:'Как называется след от удара метеорита?', a:'crater'}},
 {q:'The path of a planet around the Sun is called an ___.', o:['orbit','axis','edge','arrow'],
  why:'orbit — путь, по которому одно тело кружит вокруг другого.',
  rule:'orbit = орбита', ex:'The ISS is in orbit around the Earth.',
  again:'Axis — ось, вокруг которой планета крутится сама. Orbit — путь вокруг Солнца.',
  up:{q:'Как называется путь Земли вокруг Солнца?', a:'orbit'}},
 {q:'___ is the force that pulls everything down to the ground.', o:['Gravity','Speed','Light','Air'],
  why:'gravity — притяжение. Из-за неё яблоко падает, а Луна не улетает.',
  rule:'gravity = гравитация', ex:'There is less gravity on the Moon.',
  again:'Именно gravity держит планеты возле Солнца.',
  up:{q:'Какая сила держит нас на земле?', a:'gravity'}},
 {q:'A ___ is a huge group of billions of stars.', o:['galaxy','planet','crater','satellite'],
  why:'galaxy — галактика. Наша называется the Milky Way.',
  rule:'galaxy = галактика', ex:'We live in the Milky Way galaxy.',
  again:'Звёзд в галактике миллиарды. Планета — всего один шар.',
  up:{q:'Как называется наша галактика? (два слова)', a:'Milky Way'}},
 {q:'The ___ counts down from ten to zero before the launch.', o:['countdown','launch pad','engine','crew'],
  why:'countdown — обратный отсчёт: ten, nine, eight …',
  rule:'countdown = обратный отсчёт', ex:'The countdown has started!',
  again:'count — считать, down — вниз. Считать вниз.',
  up:{q:'Как по-английски «обратный отсчёт»?', a:'countdown'}},
 {q:'The people who fly on a spacecraft together are the ___.', o:['crew','team','group','class'],
  why:'crew — именно экипаж корабля или самолёта.',
  rule:'crew = экипаж', ex:'The crew of four landed safely.',
  again:'Team — команда в игре. Crew — команда на борту.',
  up:{q:'Как по-английски «экипаж»?', a:'crew'}},
 {q:'A ___ is an object that goes around a planet, like the Moon.', o:['satellite','star','comet','crater'],
  why:'satellite — спутник. Бывает природный (Луна) и сделанный людьми.',
  rule:'satellite = спутник', ex:'The Moon is a natural satellite of the Earth.',
  again:'Star светит сам. Satellite просто кружит рядом.',
  up:{q:'Как по-английски «спутник»?', a:'satellite'}}
]
};
