// Банк заданий Mission Control — английский язык, Grade 3–4 (Common Core ELA)
// Разбор построен по тому же правилу, что и в bank_subjects.js:
// why — что пошло не так в голове, rule — правило целиком,
// ex — разбор по шагам, again — заход с другой стороны,
// up — ДРУГОЙ пример, не повтор разобранного.
const SKILLS = [
  {id:'s3', name:'Хвостик -s', full:'He / She / It + глагол с -s', icon:'🛰️'},
  {id:'past', name:'Прошедшее время', full:'Неправильные глаголы: go → went', icon:'🌑'},
  {id:'cont', name:'Прямо сейчас', full:'am / is / are + глагол-ing', icon:'🚀'},
  {id:'prep', name:'Где что', full:'in, on, at, under, between, above', icon:'🧭'},
  {id:'plur', name:'Много', full:'Множественное число, в т.ч. хитрое', icon:'✨'},
  {id:'comp', name:'Сравнение', full:'bigger, hotter, more beautiful … than', icon:'⚖️'},
  {id:'art', name:'a / an / the', full:'Артикли', icon:'🔭'},
  {id:'read', name:'Чтение', full:'Понять текст и ответить', icon:'📡'},
  {id:'voc', name:'Словарь', full:'Космические слова', icon:'👨‍🚀'}
];

const PLANETS = {
  s3:{n:'Mercury', f:'Mercury is the smallest planet. It moves around the Sun faster than any other planet — one year there lasts only 88 days.'},
  past:{n:'Venus', f:'Venus spins backwards. If you stood there, the Sun would rise in the west and set in the east.'},
  cont:{n:'Mars', f:'Right now robots are driving on Mars. Perseverance is looking for signs of ancient life in an old river delta.'},
  prep:{n:'Jupiter', f:'A giant storm called the Great Red Spot has been turning on Jupiter for more than 300 years. Earth could fit inside it.'},
  plur:{n:'Saturn', f:'Saturn has 274 moons — more than any other planet. Its rings are made of billions of pieces of ice.'},
  comp:{n:'Uranus', f:'Uranus is colder than Neptune, even though it sits closer to the Sun. It rolls on its side like a barrel.'},
  art:{n:'Neptune', f:'The winds on Neptune are the fastest in the Solar System — up to 2,000 km per hour.'},
  read:{n:'Pluto', f:'Pluto has a huge heart-shaped glacier of frozen nitrogen. We only saw it clearly in 2015.'},
  voc:{n:'Deep Space', f:'The nearest star after the Sun is Proxima Centauri. Light from it travels 4 years to reach your eyes.'}
};

const BANK = {
s3:[
 {q:'He ___ to the space station every morning.', o:['goes','go','going','gone'],
  why:'Ты поставил глагол в начальной форме, как будто речь идёт о нескольких людях. Но подлежащее тут одно лицо, и глагол обязан на это откликнуться.',
  rule:'В настоящем простом времени глагол меняется в зависимости от того, кто действует. Для I, you, we, they он остаётся как есть. А для he, she, it — то есть для одного человека или предмета — получает окончание -s. Это единственное место, где глагол настоящего времени вообще меняет форму, поэтому английский за ним следит особенно строго. Проверка простая: если можешь заменить подлежащее на «он», «она» или «оно», ставь -s.',
  ex:'I go — we go — they go (без хвостика)\nHe goes — she goes — it goes (с хвостиком)\nHe goes to the space station every morning.',
  again:'Считай хвостик -s платой за единственность. Один — платит, много — не платит. Причём платит именно глагол, а не существительное.',
  up:{q:'My sister ___ (want) to be an astronaut.', a:'wants'}},

 {q:'The rover ___ pictures of Mars.', o:['takes','take','taking','took'],
  why:'Здесь подлежащее — предмет, и его легко не заметить. The rover — это один марсоход, то есть it.',
  rule:'Правило про -s работает не только с людьми. Любой один предмет — это it, и глагол рядом с ним получает окончание. The rover takes, the engine starts, the robot moves. Если предметов несколько, окончание уходит к существительному, а глагол остаётся чистым: the rovers take. Хвостик -s в предложении обычно только один — либо у подлежащего, либо у глагола.',
  ex:'The rover takes pictures. (один марсоход)\nThe rovers take pictures. (несколько)\nЗаметь, как -s перепрыгивает с глагола на существительное.',
  again:'Посмотри, где стоит -s. Если у существительного — значит их много, и глаголу хвостик не нужен. Если существительное без -s — глагол его забирает.',
  up:{q:'The telescope ___ (show) faraway stars.', a:'shows'}},

 {q:'My brother and I ___ the stars at night.', o:['watch','watches','watching','watched'],
  why:'Подлежащее длинное, и в глаза бросается слово brother — одно лицо. Но фраза целиком означает «мы», а это уже не один человек.',
  rule:'Когда подлежащее состоит из нескольких частей, соединённых словом and, оно становится множественным, даже если каждая часть по отдельности единственная. My brother and I — это we. Tom and Anna — это they. И глагол берёт форму без -s. Ошибка тут случается потому, что взгляд цепляется за ближайшее слово, а решает вся группа целиком.',
  ex:'My brother watches. (один)\nMy brother and I watch. (мы — двое)\nTom and Anna watch. (они)',
  again:'Замени всю группу одним местоимением. Получилось we или they — глагол без хвостика. Получилось he, she, it — с хвостиком.',
  up:{q:'Mike and his friends ___ (build) a model rocket.', a:'build'}},

 {q:'Anna ___ about becoming an astronaut.', o:['dreams','dream','dreaming','dreamt'],
  why:'Имя человека — это тоже он или она, просто названные по-другому. Глагол должен это учитывать.',
  rule:'Собственное имя одного человека равносильно местоимению he или she, поэтому глагол получает -s. Anna dreams, Tom reads, Yuri flies. Многие ошибаются потому, что в списке правил видят именно «he, she, it» и не переносят это на имена. А имя — это и есть he или she, просто конкретный.',
  ex:'Anna dreams. = She dreams.\nTom reads. = He reads.\nAnna and Tom dream. = They dream. (уже без хвостика)',
  again:'Мысленно замени имя местоимением — и правило станет видно. Anna → she → dreams.',
  up:{q:'Yuri ___ (train) for the mission every day.', a:'trains'}},

 {q:'It ___ very cold on Mars at night.', o:['gets','get','getting','got'],
  why:'It — самый прямой сигнал для окончания -s, но его часто пропускают, потому что it кажется «пустым» словом.',
  rule:'Слово it всегда обозначает один предмет, одно явление или одну ситуацию — значит, глагол рядом с ним получает -s. Это верно и тогда, когда it ни на что конкретное не указывает: в разговорах о погоде, времени и расстоянии. It gets cold, it rains, it takes an hour. Такое it называют формальным, но на глагол оно действует ровно так же.',
  ex:'It gets cold at night.\nIt rains on Titan, but with methane.\nIt takes eight minutes for sunlight to reach Earth.',
  again:'It по смыслу всегда «одно». Одно — значит хвостик обязателен, даже если непонятно, о чём именно речь.',
  up:{q:'It ___ (need) a lot of fuel.', a:'needs'}},

 {q:'Astronauts ___ special suits in space.', o:['wear','wears','wearing','wore'],
  why:'Подлежащее уже во множественном числе — на это указывает -s в конце слова astronauts. Второй раз хвостик не нужен.',
  rule:'Окончание -s означает разное у существительного и у глагола. У существительного оно говорит «их много», у глагола — «он один». Поэтому в правильном предложении эти два -s не встречаются вместе: astronauts wear, но the astronaut wears. Если видишь -s сразу и там, и там — почти наверняка ошибка.',
  ex:'The astronaut wears a suit. (один + хвостик у глагола)\nAstronauts wear suits. (много + хвостик у существительного)',
  again:'Представь, что хвостик -s один на двоих и его надо кому-то отдать. Много людей — забирает существительное. Один — забирает глагол.',
  up:{q:'Scientists ___ (work) at the space centre.', a:'work'}},

 {q:'The Sun ___ light to all the planets.', o:['gives','give','giving','gave'],
  why:'Солнце одно во всей Солнечной системе, значит подлежащее единственное, и глагол берёт -s.',
  rule:'Единственные в своём роде предметы — Солнце, Луна, Земля, небо — грамматически ведут себя как it. К ним глагол идёт с окончанием: the Sun gives, the Moon shines, the Earth moves. Размер предмета роли не играет: важно только количество, а не величина.',
  ex:'The Sun gives light.\nThe Moon shines at night.\nThe Earth moves around the Sun.',
  again:'Спроси себя: сколько их? Одно Солнце, одна Луна, одна Земля. Один — значит с хвостиком.',
  up:{q:'The star ___ (burn) for billions of years.', a:'burns'}},

 {q:'Does the telescope ___ well?', o:['work','works','working','worked'],
  why:'В предложении уже есть does — и оно забрало на себя всю работу по обозначению единственности. Глаголу окончание больше не положено.',
  rule:'В вопросах и отрицаниях появляется вспомогательный глагол do или does. Именно он показывает лицо и число: does для he, she, it и do для остальных. А основной глагол после него всегда стоит в начальной форме, без -s. Правило легко запомнить так: хвостик в предложении один, и если его уже взял does, основному глаголу ничего не остаётся.',
  ex:'The telescope works. (утверждение, хвостик у глагола)\nDoes the telescope work? (вопрос, хвостик ушёл в does)\nIt doesn\'t work. (отрицание, хвостик тоже в does)',
  again:'Сравни две фразы: He goes и Does he go? Во второй -s переехал в начало предложения и приклеился к do.',
  up:{q:'Does she ___ (need) a spacesuit?', a:'need'}}
],

past:[
 {q:'Yuri Gagarin ___ into space in 1961.', o:['went','goed','go','gone'],
  why:'Ты применил обычное правило и добавил -ed. Но глагол go не подчиняется этому правилу — он меняется целиком.',
  rule:'В английском есть две группы глаголов. Правильные образуют прошедшее время окончанием -ed: work → worked, play → played. Неправильные меняются непредсказуемо, и их формы приходится запоминать: go → went, see → saw, take → took. Неправильных не так много, около двух сотен, но именно они встречаются чаще всего — потому что это самые старые и самые ходовые слова языка.',
  ex:'work → worked (правильный, по правилу)\ngo → went (неправильный, форма другая)\nYuri Gagarin went into space in 1961.',
  again:'Формы goed не существует вообще. Если сомневаешься, вспомни фразу, которую слышал: «I went home» — так говорят всегда, и никто не скажет «I goed home».',
  up:{q:'He ___ (come) home late.', a:'came'}},

 {q:'The astronaut ___ a photo of the Earth.', o:['took','taked','take','taken'],
  why:'Снова попытка приклеить -ed к неправильному глаголу. У take прошедшее время меняет корень, а не конец.',
  rule:'У неправильных глаголов часто меняется гласная внутри слова, а не окончание: take → took, give → gave, sing → sang. Эти изменения достались языку от древних времён и не подчиняются логике, поэтому их учат как отдельные слова. Полезно запоминать сразу тройками: take — took — taken, потому что третья форма понадобится позже.',
  ex:'take → took → taken\ngive → gave → given\nThe astronaut took a photo of the Earth.',
  again:'Слушай, как звучит. «He taked a photo» режет слух даже без правил, а «he took a photo» звучит привычно — именно потому, что так говорят на самом деле.',
  up:{q:'He ___ (write) a letter.', a:'wrote'}},

 {q:'We ___ the stars through a telescope last night.', o:['saw','seen','see','sawed'],
  why:'Ты взял третью форму глагола вместо второй. Seen существует, но сама по себе, без помощника, она работать не может.',
  rule:'У неправильных глаголов три формы, и путать вторую с третьей — самая частая ошибка. Вторая форма (saw) — это простое прошедшее, она употребляется сама: I saw a comet. Третья форма (seen) — причастие, ей обязательно нужен помощник have или has: I have seen a comet. Если помощника рядом нет, ставь вторую форму.',
  ex:'see → saw → seen\nI saw a comet yesterday. (без помощника — вторая форма)\nI have seen a comet. (с have — третья форма)',
  again:'Проверь по наличию have или has. Есть — ставь третью форму. Нет — только вторую.',
  up:{q:'He ___ (see) the rocket launch.', a:'saw'}},

 {q:'The rocket ___ up into the sky.', o:['flew','flied','fly','flown'],
  why:'Здесь сработала привычка к правилу «y меняется на i». Но это правило про множественное число существительных, а не про прошедшее время неправильных глаголов.',
  rule:'Правила одной темы нельзя механически переносить на другую. У существительных на -y во множественном числе действительно появляется -ies: city → cities. Но глагол fly неправильный, и в прошедшем времени он превращается в flew. Похожие изменения у draw → drew, know → knew, grow → grew — целая группа меняет окончание на -ew.',
  ex:'fly → flew\ngrow → grew\nknow → knew\nThe rocket flew up into the sky.',
  again:'Запомни группу целиком: fly, grow, know, throw, draw. Все они в прошедшем времени заканчиваются на -ew.',
  up:{q:'He ___ (throw) the ball.', a:'threw'}},

 {q:'She ___ a book about black holes.', o:['read','readed','reads','reading'],
  why:'На письме форма не изменилась, и кажется, что глагол остался в настоящем времени. Но у read прошедшее время отличается только звучанием.',
  rule:'Глагол read — единственный в своём роде: настоящее и прошедшее время пишутся одинаково, а произносятся по-разному. В настоящем это [рид], в прошедшем — [ред]. Понять, какое время имеется в виду, можно только по смыслу предложения: по словам yesterday, last night, а иногда просто по контексту. В речи разница слышна сразу, на письме её приходится вычислять.',
  ex:'I read books every day. — звучит [рид], настоящее\nI read that book last week. — звучит [ред], прошедшее\nПишется одинаково, слышится по-разному.',
  again:'Ищи в предложении указатель времени: last week, yesterday, in 2020. Он и подскажет, как читать слово вслух.',
  up:{q:'We ___ (buy) tickets yesterday.', a:'bought'}},

 {q:'The crew ___ breakfast before the launch.', o:['had','haved','has','having'],
  why:'Have — один из самых частых глаголов, и он неправильный. Окончание -ed к нему не приклеивается.',
  rule:'У глагола have в настоящем времени две формы: have и has. А в прошедшем — всего одна, had, и она годится для всех лиц сразу. I had, he had, they had — разницы нет. Это приятное исключение: в прошедшем времени английские глаголы вообще не меняются по лицам, и have не исключение.',
  ex:'Настоящее: I have, he has\nПрошедшее: I had, he had, they had — одинаково\nThe crew had breakfast before the launch.',
  again:'Обрати внимание: в прошедшем времени английский вообще перестаёт различать лица. Хвостик -s там не появляется никогда.',
  up:{q:'He ___ (have) a question for the pilot.', a:'had'}},

 {q:'They ___ the rover to Mars in 2020.', o:['sent','sended','send','sending'],
  why:'Попытка добавить -ed к глаголу, у которого конец слова меняется сам.',
  rule:'Есть группа неправильных глаголов, у которых на конце -d превращается в -t: send → sent, build → built, spend → spent, lend → lent. Изменение небольшое, всего одна буква, поэтому такие глаголы часто ошибочно принимают за правильные. Но -ed к ним не добавляется никогда.',
  ex:'send → sent\nbuild → built\nspend → spent\nThey sent the rover to Mars in 2020.',
  again:'Эти глаголы легко запомнить вместе: send, build, spend, lend. Все меняют -d на -t и на этом успокаиваются.',
  up:{q:'She ___ (lend) me a pen.', a:'lent'}},

 {q:'The engineers ___ a new spacecraft.', o:['built','builded','build','building'],
  why:'Тот же случай, что и с send: глагол выглядит обычным, но входит в группу неправильных.',
  rule:'Build относится к той же семье, где -d на конце становится -t. Правильные и неправильные глаголы внешне ничем не отличаются — по виду слова угадать невозможно. Единственный способ — запоминать формы, а в спорном случае проверять. Хорошая новость в том, что неправильных глаголов немного и почти все они очень употребительные, так что запоминаются сами собой.',
  ex:'build → built\nЗа этот год they built two rockets.\nСравни с правильным: they painted the rocket.',
  again:'Проверь себя вслух: «builded» не встречается ни в одной песне и ни в одном фильме. А «built» слышно постоянно.',
  up:{q:'They ___ (make) a poster.', a:'made'}}
]
};
Object.assign(BANK,{
cont:[
 {q:'Look! The rocket ___ off right now.', o:['is taking','takes','take','took'],
  why:'Ты поставил обычное настоящее время, а оно рассказывает про постоянные привычки. Здесь же речь о том, что происходит в эту самую секунду.',
  rule:'В английском два разных настоящих времени, и они не взаимозаменяемы. Простое настоящее говорит о том, что бывает регулярно: every day, usually, always. Длительное — о том, что идёт прямо сейчас, в момент речи, и строится из двух частей: am, is или are плюс глагол с окончанием -ing. Пропустить первую часть нельзя: без am, is или are предложение разваливается.',
  ex:'The rocket takes off at 9 a.m. every Monday. (расписание)\nLook! The rocket is taking off right now. (в эту минуту)',
  again:'Слова-сигналы для длительного времени: now, right now, at the moment, look!, listen!. Увидел любое из них — нужна пара «is + ing».',
  up:{q:'Listen! The baby ___ (cry).', a:'is crying'}},

 {q:'The astronauts ___ an experiment at the moment.', o:['are doing','is doing','do','does'],
  why:'Время выбрано верно, но перепутан помощник. Астронавтов несколько, значит нужен are, а не is.',
  rule:'Помощник выбирается по подлежащему и только по нему: I — am, he, she, it — is, we, you, they — are. Окончание -ing при этом не меняется никогда, оно одинаково для всех. Поэтому строить фразу удобно в два шага: сначала подобрать помощника под подлежащее, потом приклеить -ing к глаголу.',
  ex:'I am doing — he is doing — they are doing\nThe astronaut is doing an experiment. (один)\nThe astronauts are doing an experiment. (несколько)',
  again:'Шаг первый — кто действует, шаг второй — что делает. Если сразу думать о глаголе, помощник легко выпадает.',
  up:{q:'The engineers ___ (check) the engine.', a:'are checking'}},

 {q:'I ___ a picture of the Moon now.', o:['am drawing','is drawing','are drawing','draw'],
  why:'К местоимению I подставлен чужой помощник. У I он свой собственный и ни с кем не делится.',
  rule:'Форма am существует ровно для одного слова — для I. Больше она не встречается нигде. Are обслуживает we, you и they, is достаётся he, she и it. Такое разделение осталось от старого английского, где глагол менялся у каждого лица по-своему; со временем формы упростились, но у I своя сохранилась.',
  ex:'I am drawing. (только так)\nYou are drawing.\nHe is drawing.',
  again:'Запомни как факт: am ходит парой с I и больше ни с кем. Это единственное слово, которому досталась личная форма.',
  up:{q:'I ___ (write) a letter to my grandma.', a:'am writing'}},

 {q:'She ___ her spacesuit right now.', o:['is putting on','puts on','are putting on','put on'],
  why:'Здесь нужно было принять два решения сразу: какое время и какой помощник. Одно из них оказалось неверным.',
  rule:'Постройка длительного времени всегда идёт по одной схеме: определить, происходит ли действие сейчас, и если да — подобрать помощника по подлежащему, а к глаголу добавить -ing. She — одно лицо, значит is. Момент речи — значит -ing. Обе части обязательны: пропустишь помощника, и получится незаконченная фраза, пропустишь -ing — получится другое время.',
  ex:'She is putting on her spacesuit. ✓\nShe putting on — нет помощника ✗\nShe is put on — нет -ing ✗',
  again:'Проверяй фразу по двум галочкам: помощник на месте и -ing на месте. Обе стоят — предложение собрано.',
  up:{q:'He ___ (open) the hatch.', a:'is opening'}},

 {q:'We ___ to the countdown at the moment.', o:['are listening','is listening','listen','listened'],
  why:'Подлежащее we — это несколько человек, и помощник должен быть множественным.',
  rule:'Три местоимения — we, you, they — берут одну и ту же форму are. Обрати внимание на you: оно означает и «ты», и «вы», но помощник у него всегда множественный, are, даже когда обращаются к одному человеку. Это след старой вежливой формы, которая вытеснила единственное число окончательно.',
  ex:'We are listening.\nYou are listening. (и к одному, и ко многим)\nThey are listening.',
  again:'Собери троицу вместе: we, you, they → are. Запомнив её одним куском, ошибаться будешь реже.',
  up:{q:'They ___ (wait) for the signal.', a:'are waiting'}},

 {q:'Every day the station ___ around the Earth 16 times.', o:['goes','is going','go','going'],
  why:'Здесь ловушка: хочется поставить длительное время, потому что станция действительно летит прямо сейчас. Но предложение говорит не о моменте, а о постоянном порядке вещей.',
  rule:'Выбор времени определяется не тем, что происходит в реальности, а тем, о чём именно сообщает предложение. Слова every day, usually, always, often, never говорят о регулярности — значит нужно простое настоящее. Слова now, at the moment указывают на момент речи — значит длительное. Станция вращается постоянно, но фраза с every day рассказывает про её обычный режим, а не про эту секунду.',
  ex:'Every day the station goes around the Earth 16 times. (порядок вещей)\nRight now the station is going over Africa. (этот момент)',
  again:'Сначала найди в предложении слово времени, потом уже выбирай форму глагола. Слово времени всегда важнее ощущения.',
  up:{q:'She ___ (work) at NASA every day.', a:'works'}},

 {q:'What ___ you ___ ?', o:['are / doing','is / doing','do / doing','are / do'],
  why:'В вопросе части предложения меняются местами, и помощник должен уйти вперёд подлежащего.',
  rule:'Вопрос в длительном времени строится по порядку: вопросительное слово, затем помощник, затем подлежащее, затем глагол с -ing. Помощник перепрыгивает через подлежащее, а окончание -ing остаётся на месте. Никаких дополнительных do или does добавлять не нужно — в этом времени свой помощник уже есть, и второго не требуется.',
  ex:'You are doing. → What are you doing?\nHe is going. → Where is he going?\nThey are eating. → What are they eating?',
  again:'Возьми утвердительное предложение и просто переставь помощника в начало. Всё остальное останется на своих местах.',
  up:{q:'Where ___ she ___ (run)?', a:'is running'}},

 {q:'The Sun ___ brightly today.', o:['is shining','shines bright','are shining','shine'],
  why:'Слово today указывает на текущий период, а Солнце одно — значит нужны is и окончание -ing.',
  rule:'Слово today относится к длящемуся сейчас отрезку времени, поэтому обычно требует длительной формы. Дальше действует обычная схема: подлежащее единственное — берём is, действие идёт — добавляем -ing. Заодно обрати внимание на само слово brightly: это наречие, оно описывает, как происходит действие, и у него есть окончание -ly. Прилагательное bright описывало бы предмет, а не действие.',
  ex:'The Sun is shining brightly today.\nsun — предмет, shining — действие, brightly — как именно\nСравни: a bright sun (какое солнце) и shines brightly (как светит)',
  again:'Два вопроса подряд: сколько их — одно, значит is. Когда — сегодня, сейчас, значит -ing.',
  up:{q:'The engine ___ (make) a loud noise.', a:'is making'}}
],

prep:[
 {q:'The satellite is ___ the Earth.', o:['above','in','at','between'],
  why:'Нужен предлог, который означает «выше и не касаясь». Спутник висит над планетой, не прикасаясь к ней.',
  rule:'Предлоги места описывают положение предметов друг относительно друга, и разница между ними бывает тонкой. Above означает «выше чего-то», без всякого касания: лампа над столом, спутник над Землёй. On тоже означает «сверху», но обязательно с прикосновением: книга на столе. Under — противоположность above, «ниже, под». Перепутать above и on легко именно потому, что оба про «сверху».',
  ex:'The lamp is above the table. (висит, не касается)\nThe book is on the table. (лежит, касается)\nThe cat is under the table. (внизу)',
  again:'Задай себе один вопрос: касается или нет. Касается — on. Не касается, но выше — above.',
  up:{q:'The book lies ___ the table and touches it. (on / above)', a:'on'}},

 {q:'We landed ___ the Moon.', o:['on','in','at','under'],
  why:'Речь о посадке на поверхность, а не внутрь. Для поверхностей английский использует on.',
  rule:'Разница между in и on — это разница между «внутри» и «на поверхности». In означает нахождение в объёме, в замкнутом пространстве: in the box, in the room, in the water. On — расположение на плоскости или поверхности: on the table, on the wall, on the Moon. С небесными телами английский считает поверхность: on Mars, on the Moon, on Earth — потому что стоят на них, а не находятся внутри.',
  ex:'on the Moon, on Mars, on Earth (на поверхности)\nin the spacecraft, in the box (внутри)\nWe landed on the Moon.',
  again:'Мысленно проверь: можно ли туда залезть внутрь? В коробку можно — in. На Луну нельзя залезть внутрь, на ней стоят — on.',
  up:{q:'The samples are ___ the box. (in / on)', a:'in'}},

 {q:'Mars is ___ Earth and Jupiter.', o:['between','among','in','on'],
  why:'Речь о положении ровно посередине двух объектов. Для двух используется свой предлог.',
  rule:'Between означает «между двумя» — предметы можно перечислить по именам, и их ровно два. Among означает «среди многих», в толпе или массе, где отдельные предметы не выделяются. Отсюда и подсказка: если после предлога идёт конструкция с and, где названы оба объекта, нужно between. Если речь об окружении неопределённым множеством — among.',
  ex:'Mars is between Earth and Jupiter. (два соседа, оба названы)\nThe star is among millions of others. (среди множества)',
  again:'Посчитай объекты. Два, и оба названы — between. Много и без имён — among.',
  up:{q:'How many things does the word between connect? (цифра)', a:'2'}},

 {q:'There is water ___ the ice on Europa.', o:['under','on','at','above'],
  why:'Океан спрятан ниже ледяной корки, значит нужен предлог «под».',
  rule:'Under — предлог нижнего положения, прямая противоположность above. Он означает «ниже чего-либо», обычно накрытого сверху: под столом, подо льдом, под одеялом. Полезно держать эти предлоги парами — above и under, over и below: так они запоминаются как система, а не как отдельные слова.',
  ex:'above — выше\nunder — ниже\nThere is water under the ice on Europa.',
  again:'Нарисуй рисунок: сверху лёд, под ним вода. Слово «под» на английском — under.',
  up:{q:'Is the floor above or below your feet?', a:'below'}},

 {q:'The astronaut is ___ the spacecraft.', o:['in','on','at','above'],
  why:'Человек находится внутри корабля, в замкнутом пространстве. Это случай для in.',
  rule:'In используется, когда предмет окружён со всех сторон: внутри комнаты, коробки, машины, корабля. Транспорт при этом делится: в маленький залезают — in the car, in the spacecraft, а на большой поднимаются — on the bus, on the plane, on the train. Разница историческая и связана с тем, можно ли внутри ходить, но запомнить проще как список.',
  ex:'in the car, in the spacecraft (маленькое, залезаешь)\non the bus, on the plane (большое, заходишь и ходишь)\nThe astronaut is in the spacecraft.',
  again:'Если внутри можно встать в полный рост и пройтись — обычно on. Если только сидеть — in.',
  up:{q:'The pilot is ___ the plane. (in / on)', a:'on'}},

 {q:'The launch is ___ 9 o\'clock.', o:['at','in','on','under'],
  why:'Названо точное время — час и минуты. Для точки во времени используется свой предлог.',
  rule:'Предлоги времени устроены как лестница от точного к общему. At — для конкретного момента: at 9 o\'clock, at noon, at midnight. On — для дня: on Monday, on May 5th. In — для длинных отрезков: in April, in 2026, in summer. Чем крупнее промежуток, тем «шире» предлог, и эта лесенка работает почти без исключений.',
  ex:'at 9 o\'clock (момент)\non Monday (день)\nin April (месяц)\nin 2026 (год)',
  again:'Запомни лесенку целиком: at — час, on — день, in — месяц и год. По ней потом легко разобрать любой случай.',
  up:{q:'The meeting starts ___ 6 o\'clock.', a:'at'}},

 {q:'Gagarin flew into space ___ 1961.', o:['in','at','on','under'],
  why:'Год — большой отрезок времени, и для него нужна верхняя ступенька лесенки.',
  rule:'In отвечает за крупные промежутки: годы, месяцы, времена года, века. Логика простая — событие происходит где-то внутри этого отрезка, а не в конкретную его точку. Полёт Гагарина случился в течение 1961 года, поэтому in 1961. Если бы мы назвали дату целиком, потребовался бы on: on April 12, 1961.',
  ex:'in 1961 (год)\nin April (месяц)\non April 12 (день)\nat 9:07 a.m. (точное время старта)',
  again:'Та же лесенка, только сверху вниз: in — год, on — день, at — час. Чем точнее время, тем «уже» предлог.',
  up:{q:'The rover landed ___ 2021.', a:'in'}},

 {q:'The launch happened ___ Monday.', o:['on','in','at','above'],
  why:'Назван день недели — это средняя ступенька лесенки времени.',
  rule:'On используется для дней: дней недели, конкретных дат, праздников. On Monday, on May 5th, on my birthday. Заметь, что этот же предлог отвечает за поверхности — on the table. Связь тут есть: день мыслится как площадка, на которой располагаются события, поэтому предлог тот же.',
  ex:'on Monday\non May 5th\non New Year\'s Day\nСравни: on the table — тот же предлог, другая область.',
  again:'День — это средняя ступенька: at (час) → on (день) → in (год).',
  up:{q:'We have a lesson ___ Friday.', a:'on'}}
]
});
Object.assign(BANK,{
plur:[
 {q:'There are many ___ in the Solar System.', o:['planets','planetes','planet','planetz'],
  why:'Слово во множественном числе, но окончание выбрано неверно. Большинству существительных нужно простое -s, без добавок.',
  rule:'Основное правило множественного числа — добавить -s к слову без всяких изменений: star → stars, rocket → rockets, planet → planets. Окончание -es появляется только после шипящих и свистящих звуков, где просто -s не выговорить: box → boxes, watch → watches, dish → dishes. Всё дело в произношении: язык не успевает перейти от одного свистящего к другому, и между ними вставляется гласная.',
  ex:'planet → planets (обычное -s)\nbox → boxes (после x нужна вставка)\nwatch → watches (после ch тоже)',
  again:'Попробуй произнести «boxs» — получается невозможно. А «planets» произносится легко. Язык сам подсказывает, где нужна лишняя гласная.',
  up:{q:'one star → three ___', a:'stars'}},

 {q:'Astronauts study the ___ of other planets.', o:['skies','skys','sky','skyes'],
  why:'Слово оканчивается на -y после согласной, и в таком случае буква y не сохраняется.',
  rule:'Когда слово заканчивается на -y, важно, какая буква стоит перед ней. Если согласная, то y превращается в i и добавляется -es: sky → skies, city → cities, baby → babies. Если гласная, y остаётся на месте и добавляется простое -s: day → days, boy → boys, key → keys. Правило существует потому, что сочетание гласной с y уже образует устойчивый звук, разрушать который не надо.',
  ex:'sky → skies (перед y согласная k)\nday → days (перед y гласная a)\ncity → cities, boy → boys',
  again:'Посмотри на букву перед y, а не на саму y. Она и решает, менять или нет.',
  up:{q:'one baby → many ___', a:'babies'}},

 {q:'The rover found two ___ of ice.', o:['pieces','piecies','piece','piecs'],
  why:'Здесь сработало правило про -ies, но оно тут не применимо: слово заканчивается не на y.',
  rule:'Правило -ies работает исключительно для слов на -y после согласной. Если слово оканчивается на -e, ничего менять не надо, просто добавляется -s: piece → pieces, place → places, face → faces. Ошибка возникает, когда правило запоминают по звучанию — «пииисиз» — и достраивают лишнюю i. Смотреть надо на написание, а не на слух.',
  ex:'piece → pieces\nplace → places\nЗдесь -e уже есть, буква i не нужна.',
  again:'Проверь последнюю букву в исходном слове. Не y — значит про -ies можно забыть.',
  up:{q:'one face → two ___', a:'faces'}},

 {q:'Space suits protect the ___ of astronauts.', o:['bodies','bodys','body','bodyes'],
  why:'Перед y стоит согласная d, значит вступает в силу правило с заменой на i.',
  rule:'Body заканчивается на -y, и перед ней согласная — та же схема, что у sky и city. Y меняется на i, добавляется -es. Список таких слов длинный: story → stories, family → families, country → countries, party → parties. Все они ведут себя одинаково, и, выучив схему один раз, можно не запоминать каждое.',
  ex:'body → bodies\nstory → stories\nfamily → families\ncountry → countries',
  again:'Собери слова в один список и заметь, что они устроены одинаково. Это не отдельные исключения, а одно правило.',
  up:{q:'one party → many ___', a:'parties'}},

 {q:'Scientists sent three ___ to Mars.', o:['probes','probies','probs','probe'],
  why:'Опять правило -ies применено не по адресу. Probe оканчивается на -e, а не на -y.',
  rule:'Полезно держать в голове короткий порядок проверки. Сначала посмотри на конец слова: заканчивается на s, x, ch, sh — добавляй -es. Заканчивается на y после согласной — меняй на -ies. Во всех остальных случаях просто добавляй -s. Такой порядок закрывает почти все обычные существительные, и гадать не приходится.',
  ex:'probe → probes (обычный случай, просто -s)\ntube → tubes\ncube → cubes',
  again:'Пройди проверку по шагам: шипящий на конце? Нет. Y после согласной? Нет. Значит просто -s.',
  up:{q:'one note → five ___', a:'notes'}},

 {q:'The crew took photos of six ___ on Mars.', o:['rocks','rockes','rock','rocki'],
  why:'Окончание -es добавлено туда, где оно не требуется. После k звук произносится легко и без вставки.',
  rule:'Вставная гласная в -es нужна только после свистящих и шипящих: s, x, z, ch, sh. После остальных согласных -s произносится без затруднений, поэтому никаких добавок не нужно: rock → rocks, book → books, desk → desks. Правило целиком построено на удобстве произношения — в этом его логика.',
  ex:'rock → rocks, book → books (легко)\nbox → boxes, bush → bushes (нужна вставка)',
  again:'Скажи вслух оба варианта. «Rocks» выговаривается сразу, «rockes» звучит искусственно — значит лишнее.',
  up:{q:'one glass → two ___', a:'glasses'}},

 {q:'Two ___ work on the station.', o:['men','mans','mens','man'],
  why:'Слово man не подчиняется общим правилам: у него меняется гласная внутри, а окончание не добавляется вовсе.',
  rule:'Небольшая группа старых английских слов образует множественное число сменой гласной, без всяких окончаний: man → men, woman → women, foot → feet, tooth → teeth, goose → geese. Это остатки древней системы, которая работала до появления окончания -s. Слов таких мало, десятка полтора, и их просто заучивают.',
  ex:'man → men\nwoman → women\nfoot → feet\ntooth → teeth',
  again:'Обрати внимание: в этих словах меняется середина, а конец остаётся. Ни -s, ни -es к ним не добавляют никогда.',
  up:{q:'one goose → two ___', a:'geese'}},

 {q:'The telescope showed us new ___ .', o:['galaxies','galaxys','galaxes','galaxy'],
  why:'Galaxy оканчивается на -y после согласной x, значит работает замена на -ies.',
  rule:'Схема та же, что у sky, city и body: убираем y, ставим i, добавляем -es. Никаких исключений здесь нет, даже несмотря на непривычное сочетание букв перед окончанием. Буква x — согласная, и этого достаточно, чтобы правило сработало.',
  ex:'galaxy → galaxies\nsky → skies\nПеред y стоит согласная — значит меняем.',
  again:'Не смущайся необычным написанием слова. Правило смотрит только на одну букву — ту, что перед y.',
  up:{q:'one story → many ___', a:'stories'}}
],

comp:[
 {q:'Jupiter is ___ than Earth.', o:['bigger','more big','biggest','big'],
  why:'Со словом more построено сравнение для длинных слов, а big — короткое, и у него своя форма.',
  rule:'Способ сравнения зависит от длины слова. Короткие слова в один слог получают окончание -er: small → smaller, fast → faster, big → bigger. Длинные, из трёх слогов и больше, берут слово more: more beautiful, more interesting. Двусложные делятся: одни склоняются к -er, другие к more. Смешивать оба способа сразу нельзя — «more bigger» будет грубой ошибкой.',
  ex:'big → bigger (один слог)\nbeautiful → more beautiful (три слога)\nJupiter is bigger than Earth.',
  again:'Посчитай слоги. Один — почти всегда -er. Три и больше — точно more.',
  up:{q:'small → ___ than', a:'smaller'}},

 {q:'Venus is ___ than Mercury.', o:['hotter','hoter','more hot','hottest'],
  why:'Окончание добавлено, но последняя согласная не удвоена. В таких словах это обязательно.',
  rule:'Если короткое слово заканчивается сочетанием «согласная — гласная — согласная», то при добавлении -er последняя согласная удваивается: hot → hotter, big → bigger, thin → thinner, sad → sadder. Удвоение нужно, чтобы гласная в корне осталась короткой: без него hoter читалось бы как «хоутер». Буква выполняет работу знака произношения.',
  ex:'hot → hotter (t удваивается)\nbig → bigger (g удваивается)\nНо: fast → faster (на конце две согласные, удваивать нечего)',
  again:'Проверь три последние буквы. Согласная, гласная, согласная — удваивай. Иначе оставь как есть.',
  up:{q:'thin → ___ than', a:'thinner'}},

 {q:'A nebula is ___ than a planet.', o:['more beautiful','beautifuler','beautifullest','beautiful'],
  why:'К длинному слову приклеено окончание -er, хотя такие слова сравниваются с помощью more.',
  rule:'Длинные слова не берут окончание -er по причине произношения: beautifuler выговорить почти невозможно. Поэтому для них используется отдельное слово more, которое ставится перед прилагательным. К этой группе относятся почти все слова на -ful, -ous, -ing, -ed и большинство трёхсложных: more careful, more famous, more interesting, more difficult.',
  ex:'more beautiful, more interesting, more difficult\nПопробуй сказать beautifuler вслух — язык спотыкается.',
  again:'Произношение и есть подсказка. Если слово с -er не выговаривается, значит нужно more.',
  up:{q:'careful → ___ than', a:'more careful'}},

 {q:'This telescope is ___ than that one.', o:['better','gooder','more good','best'],
  why:'К слову good применено общее правило, но оно входит в число исключений и меняется полностью.',
  rule:'Три самых частых прилагательных английского меняются непредсказуемо: good → better → the best, bad → worse → the worst, far → farther → the farthest. Эти формы образовались задолго до появления окончания -er и сохранились как есть. Их всего три, они встречаются постоянно, поэтому запоминаются быстро.',
  ex:'good → better → the best\nThis telescope is better than that one.',
  again:'Выучи эту тройку отдельным списком. Больше исключений такого рода в сравнении почти нет.',
  up:{q:'bad → ___ than', a:'worse'}},

 {q:'The Sun is the ___ object in the Solar System.', o:['largest','larger','most large','large'],
  why:'Использована форма сравнения двух предметов, а здесь выбирают один из всех.',
  rule:'Сравнительная и превосходная степени решают разные задачи. Сравнительная сопоставляет два предмета и требует слова than: bigger than, faster than. Превосходная выделяет один из всей группы и требует артикля the: the biggest, the fastest. У длинных слов превосходная строится со словом most: the most beautiful. Артикль the тут обязателен — он и означает, что такой предмет один.',
  ex:'bigger than (сравниваем двоих)\nthe biggest (выбираем одного из всех)\nThe Sun is the largest object in the Solar System.',
  again:'Ищи в предложении слово than. Есть — нужна сравнительная форма. Нет, но есть the — нужна превосходная.',
  up:{q:'fast → the ___', a:'fastest'}},

 {q:'Neptune is ___ from the Sun than Uranus.', o:['farther','farer','more far','farthest'],
  why:'К слову far добавлено обычное окончание, но это одно из трёх исключений.',
  rule:'Far меняется на farther или further. Разница между ними тонкая: farther обычно про настоящее расстояние, further — про переносное, «дальнейший». В школьных заданиях о расстоянии используют farther. Формы farer не существует ни в одном варианте английского.',
  ex:'far → farther (о расстоянии)\nMars is farther than Venus.\nfurther information (дальнейшие сведения, не о расстоянии)',
  again:'Это третье исключение из той же тройки: good, bad, far. Все три меняются целиком.',
  up:{q:'good → ___ than', a:'better'}},

 {q:'A comet moves ___ than a planet.', o:['faster','more fast','fastest','fast'],
  why:'Короткое слово получило more, хотя ему достаточно окончания.',
  rule:'Слово fast состоит из одного слога, значит сравнительная степень образуется окончанием -er. Ставить перед ним more не нужно и нельзя: язык не допускает двойного обозначения одного и того же. Правило действует и для наречий такого вида: he runs faster, she works harder.',
  ex:'fast → faster\nhard → harder\nA comet moves faster than a planet.',
  again:'Слово из одного слога — только -er, никогда more.',
  up:{q:'slow → ___ than', a:'slower'}},

 {q:'Pluto is ___ than Mercury.', o:['smaller','more small','smallest','small'],
  why:'Тот же случай: перед коротким словом стоит лишнее more.',
  rule:'Сравнительная степень работает в паре со словом than, и эта пара почти всегда стоит вместе: smaller than, colder than, longer than. Если видишь в предложении than, значит нужна форма с -er или с more — в зависимости от длины слова, но не обе сразу. Для коротких слов это -er.',
  ex:'smaller than\ncolder than\nlonger than\nPluto is smaller than Mercury.',
  again:'Пара «-er … than» ходит вместе. Увидел than — ищи форму с окончанием.',
  up:{q:'young → ___ than', a:'younger'}}
]
});
Object.assign(BANK,{
art:[
 {q:'I saw ___ astronaut on TV yesterday.', o:['an','a','the','—'],
  why:'Выбран артикль для согласного звука, а слово astronaut начинается с гласного.',
  rule:'Артикли a и an — это одно и то же слово в двух вариантах произношения. An ставится перед гласным звуком, a — перед согласным. Причина чисто фонетическая: две гласные подряд сливаются и слово теряется, поэтому между ними вставляется n. Слышится a apple как одно слово, а an apple — как два, и смысл не смазывается.',
  ex:'an astronaut, an apple, an engineer (гласный звук)\na rocket, a star, a book (согласный звук)',
  again:'Произнеси оба варианта вслух. «A astronaut» спотыкается, «an astronaut» звучит гладко.',
  up:{q:'___ engineer (a / an)', a:'an'}},

 {q:'She wants to be ___ scientist.', o:['a','an','the','—'],
  why:'Поставлен вариант для гласного звука, хотя слово начинается с согласного.',
  rule:'Определяет выбор именно звук, а не буква. Scientist пишется с буквы s и начинается со звука [с] — значит a. Слово помогает запомнить, что английский ориентируется на произношение: в нём буквы и звуки расходятся часто, и артикль всегда слушает звук.',
  ex:'a scientist, a spacecraft, a mission\nan engineer, an orbit, an hour',
  again:'Не смотри на букву, произнеси слово. Первый звук гласный — an, согласный — a.',
  up:{q:'___ rocket (a / an)', a:'a'}},

 {q:'___ Sun is a star.', o:['The','A','An','—'],
  why:'Использован артикль, означающий «какой-то один из многих», но Солнце у нас одно.',
  rule:'Артикль a знакомит с предметом впервые и означает «один из многих такой же». The указывает на конкретный, известный собеседнику предмет. Поэтому единственные в своём роде объекты всегда идут с the: the Sun, the Moon, the Earth, the sky. Их не нужно уточнять — второго такого нет, и обе стороны понимают, о чём речь.',
  ex:'The Sun is a star. (наше Солнце одно, но звёзд много)\nОбрати внимание: the перед Sun, но a перед star.',
  again:'Спроси себя: такой предмет один на свете или их много? Один — the.',
  up:{q:'___ Moon is bright tonight. (The / A)', a:'The'}},

 {q:'I read ___ book about Mars. ___ book was great.', o:['a / The','the / A','an / The','a / A'],
  why:'Артикль в этой паре меняется: первое упоминание и второе требуют разного.',
  rule:'При первом упоминании предмет собеседнику незнаком, поэтому используется a — «какая-то книга». Во второй раз книга уже известна из разговора, она конкретная, и артикль меняется на the. Эта пара a … the устроена как знакомство: сначала представили, потом говорят как о знакомом. Правило работает в любых текстах и рассказах.',
  ex:'I read a book. The book was great.\nI saw a cat. The cat was black.\nПервый раз — a, дальше — the.',
  again:'A знакомит, the вспоминает. Услышал о предмете впервые — a, встретил его снова — the.',
  up:{q:'I have a dog. ___ dog is small. (The / A)', a:'The'}},

 {q:'It takes ___ hour to get there.', o:['an','a','the','—'],
  why:'Слово начинается с согласной буквы, и артикль выбран по букве. Но эта буква не читается.',
  rule:'В слове hour буква h немая, и слово начинается со звука [ау] — гласного. Поэтому артикль an. То же самое с honest и honour. Работает и обратный случай: university пишется с гласной u, но начинается со звука [ю], согласного, и берёт a. Оба примера показывают одно: артикль подчиняется звуку, а написание может обманывать.',
  ex:'an hour, an honest man (h не читается)\na university, a European country (звучит как [ю])',
  again:'Закрой глаза и произнеси слово. Что слышишь первым — то и решает.',
  up:{q:'___ honest answer (a / an)', a:'an'}},

 {q:'Mars is ___ fourth planet from the Sun.', o:['the','a','an','—'],
  why:'С порядковым числительным всегда идёт определённый артикль, потому что такой предмет единственный.',
  rule:'Порядковые числительные — first, second, third, fourth — выделяют один конкретный предмет в ряду. Четвёртая планета от Солнца только одна, первый астронавт только один. Поэтому перед ними стоит the. С количественными числительными всё иначе: four planets — просто количество, артикль не нужен.',
  ex:'the fourth planet, the first astronaut, the third rocket\nНо: four planets, three rockets (просто количество)',
  again:'Порядковое число указывает на место в ряду, а место всегда одно. Одно — значит the.',
  up:{q:'___ first astronaut in space (the / a)', a:'the'}},

 {q:'Astronauts need ___ oxygen to breathe.', o:['—','a','an','the'],
  why:'Артикль поставлен к слову, которое нельзя посчитать. Такие слова обходятся без него.',
  rule:'Существительные делятся на исчисляемые и неисчисляемые. Исчисляемые можно посчитать поштучно: one rocket, two rockets — и они требуют артикля в единственном числе. Неисчисляемые обозначают вещество или понятие без отдельных единиц: water, air, oxygen, music, information. Сказать «два кислорода» нельзя, и артикль a к ним не ставится. The перед ними появиться может, но только когда речь о конкретной порции.',
  ex:'a rocket, two rockets (можно посчитать)\noxygen, water, air (посчитать нельзя — без артикля)\nThe water in this glass is cold. (конкретная порция — можно the)',
  again:'Проверь вопросом: можно сказать «два таких»? Нельзя — значит артикль a не нужен.',
  up:{q:'We need ___ water. (артикль или прочерк?)', a:'—'}},

 {q:'This is ___ interesting experiment.', o:['an','a','the','—'],
  why:'Артикль выбирается по слову, которое идёт сразу за ним, а не по главному существительному.',
  rule:'Когда между артиклем и существительным стоит прилагательное, решает именно прилагательное — оно ближе. Interesting начинается с гласного звука, значит нужен an, хотя само слово experiment тоже с гласной. Правило проще всего проверять по соседству: артикль смотрит на то, что стоит непосредственно после него.',
  ex:'an experiment → an interesting experiment\na rocket → an old rocket (прилагательное поменяло артикль)\na star → a bright star',
  again:'Смотри на слово, которое стоит сразу после артикля. Оно и определяет форму.',
  up:{q:'___ old telescope (a / an)', a:'an'}}
],

voc:[
 {q:'A ___ is a machine that drives on the surface of a planet.', o:['rover','rocket','orbit','crater'],
  why:'Выбрано слово из той же области, но обозначающее другое. Различать надо по способу передвижения.',
  rule:'Слово rover происходит от глагола to rove — «бродить, странствовать». Это машина, которая ездит по поверхности планеты, изучая её: Curiosity, Perseverance, Opportunity. Rocket — ракета, она летит и доставляет груз в космос. Orbit — путь вокруг тела. Crater — углубление в грунте. Слова часто встречаются вместе в текстах о космосе, поэтому их легко перепутать, но задачи у них разные.',
  ex:'rover — ездит по поверхности\nrocket — летит в космос\norbit — путь вокруг планеты\ncrater — воронка в грунте',
  again:'Привяжи слово к действию: rover roves — бродит. Rocket летит. Разница в движении.',
  up:{q:'Does a rover fly or drive?', a:'drive'}},

 {q:'A ___ is a big hole in the ground made by a falling rock.', o:['crater','planet','comet','moon'],
  why:'Перепутан след от удара и сам летящий объект. Это разные вещи.',
  rule:'Crater — углубление, оставшееся после удара метеорита или после извержения вулкана. Comet — сам объект, ледяное тело, летящее вокруг Солнца. Разница как между следом от ботинка и ботинком. Луна вся покрыта кратерами, потому что у неё нет атмосферы, которая сжигала бы мелкие камни на подлёте, и следы от ударов сохраняются миллионы лет.',
  ex:'crater — след, углубление\ncomet — летящее ледяное тело\nThe Moon is covered with craters.',
  again:'Кратер — это дырка, и её оставили. Комета — это то, что летит. След и объект не путай.',
  up:{q:'Is a crater an object or a mark left behind? (object / mark)', a:'mark'}},

 {q:'The path of a planet around the Sun is called an ___ .', o:['orbit','axis','edge','arrow'],
  why:'Смешаны два вида вращения: вокруг чего-то другого и вокруг самого себя.',
  rule:'Orbit — путь, по которому одно тело обращается вокруг другого: Земля вокруг Солнца, Луна вокруг Земли, станция вокруг планеты. Axis — воображаемая линия внутри тела, вокруг которой оно вращается само. Из-за вращения вокруг оси происходит смена дня и ночи, а из-за движения по орбите — смена времён года. Разные движения дают разные последствия.',
  ex:'orbit — путь вокруг другого тела (год)\naxis — ось вращения самого тела (сутки)\nThe ISS is in orbit around the Earth.',
  again:'Земля делает два движения сразу: крутится вокруг оси и летит по орбите. Первое даёт день и ночь, второе — год.',
  up:{q:'Does spinning on its axis give us day and night, or the seasons? (day and night / seasons)', a:'day and night'}},

 {q:'___ is the force that pulls everything down to the ground.', o:['Gravity','Speed','Light','Air'],
  why:'Выбрано не то понятие: сила и скорость — разные вещи, одна вызывает другую.',
  rule:'Gravity — сила притяжения между телами, обладающими массой. Именно она заставляет предметы падать вниз, удерживает атмосферу у планеты и не даёт Луне улететь. Speed — скорость, то есть результат действия силы, а не сама сила. Чем больше масса тела, тем сильнее оно притягивает: на Луне притяжение слабее земного примерно в шесть раз, поэтому астронавты там подпрыгивают высоко.',
  ex:'Gravity pulls things down. (сила)\nSpeed is how fast something moves. (результат)\nThere is less gravity on the Moon.',
  again:'Сила — причина, скорость — следствие. Падает предмет из-за гравитации, а быстро или медленно — это уже скорость.',
  up:{q:'Is gravity stronger on Earth or on the Moon?', a:'Earth'}},

 {q:'A ___ is a huge group of billions of stars.', o:['galaxy','planet','crater','satellite'],
  why:'Перепутан масштаб: планета — один объект, а в вопросе речь о миллиардах звёзд.',
  rule:'Galaxy — гигантское скопление звёзд, газа и пыли, связанное гравитацией. Наша называется the Milky Way, в ней порядка ста миллиардов звёзд, и Солнце — одна из них. Планета на этом фоне крошечная: она вращается вокруг одной звезды. Порядок величин от малого к большому такой: спутник, планета, звезда, галактика.',
  ex:'satellite < planet < star < galaxy\nWe live in the Milky Way galaxy.\nThe Sun is one star among billions.',
  again:'Выстрой лесенку размеров, и слова перестанут путаться: спутник, планета, звезда, галактика.',
  up:{q:'Do we live inside a galaxy? (yes / no)', a:'yes'}},

 {q:'The ___ counts down from ten to zero before the launch.', o:['countdown','launch pad','engine','crew'],
  why:'Выбрано слово из той же сцены, но обозначающее не действие, а предмет или людей.',
  rule:'Countdown составлено из двух слов: count — считать и down — вниз. Получается «счёт в обратную сторону», от большего числа к нулю. Такие составные слова в английском встречаются часто, и их смысл обычно легко разобрать по частям: launch pad — площадка для запуска, spacecraft — космический корабль, spacesuit — скафандр.',
  ex:'countdown — обратный отсчёт (count + down)\nlaunch pad — стартовая площадка\nspacesuit — скафандр (space + suit)',
  again:'Разбирай составные слова на части — почти всегда получается точный перевод.',
  up:{q:'Does a countdown end at zero or start at zero? (end / start)', a:'end'}},

 {q:'The people who fly on a spacecraft together are the ___ .', o:['crew','team','group','class'],
  why:'Выбрано слово с близким смыслом, но из другой области: команда бывает разная, а на корабле — своя.',
  rule:'Crew — люди, работающие вместе на корабле, самолёте или космической станции, каждый со своей ролью. Team — команда в более широком смысле: спортивная, рабочая, проектная. Английский часто держит отдельные слова для похожих понятий из разных областей, и выбирать надо по месту действия: на борту это всегда crew.',
  ex:'the crew of the spacecraft (на борту)\na football team (в спорте)\nThe crew of four landed safely.',
  again:'Привяжи слово к месту: на корабле — crew, на поле — team.',
  up:{q:'Is the word crew used for a ship or for a school lesson? (ship / lesson)', a:'ship'}},

 {q:'A ___ is an object that goes around a planet, like the Moon.', o:['satellite','star','comet','crater'],
  why:'Выбрано тело, которое светит само, но в вопросе речь о том, что вращается вокруг планеты.',
  rule:'Satellite — любой объект, обращающийся вокруг планеты. Бывают природные, как Луна, и искусственные, запущенные людьми: их сейчас на орбите Земли тысячи. Star — звезда, она излучает собственный свет за счёт реакций внутри. Ключевое отличие: спутник светит отражённым светом или не светит вовсе, а звезда — источник света сама по себе.',
  ex:'The Moon is a natural satellite.\nGPS satellites are artificial.\nThe Sun is a star — it makes its own light.',
  again:'Спроси: светит само или отражает? Само — звезда. Отражает и вращается вокруг планеты — спутник.',
  up:{q:'Does a satellite make its own light? (yes / no)', a:'no'}}
]
});
Object.assign(BANK,{
read:[
 {q:'"The Perseverance rover landed in Jezero Crater in 2021. Long ago, a river flowed into this crater and made a lake. Scientists hope the rover will find signs of ancient life in the old mud."\n\nWhy did scientists choose Jezero Crater?',
  o:['Because a river and a lake were once there','Because it is the biggest crater on Mars','Because the rover landed there in 2021','Because there is water there now'],
  why:'Выбран факт из текста, но отвечающий на другой вопрос. «Сел в 2021» — это когда, а спрашивали почему.',
  rule:'Вопрос «почему» требует причины, а не любого верного факта. Самая частая ошибка в чтении — взять предложение, которое точно есть в тексте, и решить, что оно подходит. Проверять надо иначе: подставь свой ответ во фразу «это произошло, потому что…» и посмотри, получается ли осмысленно. «Выбрали кратер, потому что ровер сел туда в 2021» — бессмыслица, причина и следствие поменялись местами.',
  ex:'Вопрос: почему выбрали кратер?\nТекст: когда-то туда впадала река и было озеро\nГде вода — там могла быть жизнь → это и есть причина\n«Сел в 2021» отвечает на «когда», а не на «почему»',
  again:'Отделяй тип вопроса от содержания. Where — место, when — время, why — причина, how — способ. Ответ должен совпасть по типу.',
  up:{q:'В тексте сказано, что ровер ищет признаки чего? (одно слово)', a:'life'}},

 {q:'"A black hole is not really a hole. It is a place where gravity pulls so hard that nothing can escape — not even light. That is why we cannot see a black hole. We only see how it pulls stars and gas around it."\n\nWhy can\'t we see a black hole?',
  o:['Because light cannot escape from it','Because it is very far away','Because it is a hole in space','Because it has no stars around it'],
  why:'Выбрано объяснение, которого в тексте нет. Расстояние здесь вообще не упоминается — ответ придуман из общих соображений.',
  rule:'В заданиях на понимание отвечать можно только тем, что есть в тексте. Собственные знания и догадки, даже разумные, не годятся: проверяют не эрудицию, а умение читать. Надёжный приём — найти в тексте предложение, подтверждающее ответ, и мысленно ткнуть в него пальцем. Не находится — ответ неверный, каким бы логичным он ни казался.',
  ex:'«nothing can escape — not even light»\n«That is why we cannot see a black hole»\nОба предложения прямо в тексте → ответ подтверждён\nПро расстояние в тексте нет ни слова',
  again:'Оборот «That is why» — прямой указатель: причина стоит прямо перед ним.',
  up:{q:'Что мы видим вокруг чёрной дыры, раз саму её не видно? (два слова через and)', a:'stars and gas'}},

 {q:'"On the ISS astronauts sleep in sleeping bags fixed to the wall. If they did not do this, they would float around the station and bump into things while sleeping."\n\nWhy are the sleeping bags fixed to the wall?',
  o:['So astronauts do not float around while sleeping','Because there are no beds on the station','Because the wall is warmer','So astronauts can see the Earth'],
  why:'Выбрано правдоподобное объяснение, но текст его не подтверждает. Про кровати и тепло там ничего не сказано.',
  rule:'Иногда причина в тексте подана через воображаемое последствие: «если бы не делали так, случилось бы вот это». Такая конструкция описывает, чего именно избегают, и именно она и есть причина. Ищи обороты if … would, otherwise, so that — они часто прячут ответ на вопрос «почему».',
  ex:'«If they did not do this, they would float around»\nЧего избегают: летать по станции во сне\nЗначит спальники крепят именно ради этого',
  again:'Переверни условную фразу в прямую: чтобы не летать по станции, спальники пристёгивают к стене.',
  up:{q:'В чём спят астронавты на станции? (два слова)', a:'sleeping bags'}},

 {q:'"Saturn\'s rings look solid from far away. But they are made of billions of pieces of ice and rock. Some pieces are as small as a grain of sand. Others are as big as a house."\n\nWhat are Saturn\'s rings made of?',
  o:['Pieces of ice and rock','One solid piece of ice','Sand from Saturn','Gas and dust'],
  why:'Взято слово solid, которое в тексте есть, но с важной оговоркой: кольца только выглядят сплошными.',
  rule:'Обращай внимание на слова, меняющие смысл предложения: look, seem, appear означают «кажется», а не «является». Ещё сильнее меняет смысл слово but — после него обычно идёт настоящее положение дел, а до него то, что только кажется. Пропустить but значит понять текст наоборот.',
  ex:'«look solid from far away» — только выглядят\n«But they are made of billions of pieces» — на самом деле\nСлово but и переключает с видимости на суть',
  again:'Найди в тексте but и прочитай, что идёт после него. Там почти всегда главное.',
  up:{q:'С чем в тексте сравнивают самые мелкие кусочки колец? (три слова)', a:'a grain of sand'}},

 {q:'"The Moon has no air. Because of this, sound cannot travel there. If you shouted on the Moon, your friend standing next to you would hear nothing."\n\nWhat is the main idea of this text?',
  o:['There is no sound on the Moon because there is no air','The Moon is a dangerous place for people','Friends should not shout at each other','The Moon is very far from Earth'],
  why:'Выбрано утверждение, которого в тексте нет, — про опасность Луны там не говорится ни слова.',
  rule:'Главная мысль объединяет весь текст, а не пересказывает одну деталь. Чтобы её найти, прочитай все предложения и спроси: о чём они все вместе? Здесь все три — про отсутствие воздуха и вытекающее отсюда отсутствие звука. Ответ, подходящий только к одному предложению, — слишком узкий, а ответ, которого в тексте нет вовсе, — просто неверный.',
  ex:'1: на Луне нет воздуха\n2: поэтому звук не распространяется\n3: крик не услышат даже рядом\nВсе три об одном → нет воздуха, нет звука',
  again:'Проверь выбранный ответ на каждом предложении по очереди. Подходит ко всем — это главная мысль. Подходит к одному — деталь.',
  up:{q:'Чего нет на Луне, из-за чего не слышно звука? (одно слово)', a:'air'}},

 {q:'"Comets come from the cold outer edge of the Solar System. When a comet flies near the Sun, its ice starts to melt. The gas and dust form a long bright tail that always points away from the Sun."\n\nWhen does a comet get its tail?',
  o:['When it flies near the Sun','When it is far from the Sun','When it hits a planet','When it is made of ice'],
  why:'Хвост направлен от Солнца — и из этого сделан вывод, что и появляется он вдали от Солнца. Но это разные вещи: куда указывает и когда возникает.',
  rule:'Направление и момент возникновения — две независимые характеристики, и текст может говорить о них в одном предложении. Здесь хвост появляется вблизи Солнца, потому что именно там тает лёд, а указывает при этом в противоположную сторону. Читая, разделяй такие детали: «когда» отвечает на вопрос о времени, «куда» — о направлении.',
  ex:'Когда появляется: when a comet flies near the Sun\nКуда направлен: away from the Sun\nЭто разные сведения в одном предложении',
  again:'Слово when в тексте — прямая подсказка для вопроса «когда». Оно тут стоит в начале второго предложения.',
  up:{q:'Что начинает таять, когда комета подлетает к Солнцу? (одно слово)', a:'ice'}},

 {q:'"Astronauts exercise two hours every day. In space, muscles and bones become weak because there is almost no gravity to work against. Exercise keeps the body strong for the return to Earth."\n\nWhy do astronauts exercise so much?',
  o:['Because muscles get weak without gravity','Because they have a lot of free time','Because exercise is fun in space','Because they want to grow taller'],
  why:'Возможно, сработала подстановка первого числа из текста. Два часа в день — это сколько, а не почему.',
  rule:'Числа в тексте притягивают внимание, но редко бывают ответом на вопрос «почему». Причина обычно вводится словом because или стоит в предложении, объясняющем предыдущее. Здесь второе предложение прямо говорит: мышцы слабеют, потому что нет гравитации, с которой нужно бороться. Это и есть причина, а два часа — мера.',
  ex:'«muscles and bones become weak because there is almost no gravity»\nСлово because — прямой указатель причины\nДва часа в день отвечают на «сколько»',
  again:'Ищи в тексте because, so, that is why. Эти слова почти всегда стоят рядом с ответом на «почему».',
  up:{q:'Сколько часов в день занимаются астронавты? (цифра)', a:'2'}},

 {q:'"The James Webb telescope does not look at the sky in normal light. It sees infrared — a kind of light our eyes cannot catch. This lets it look through clouds of dust and see the very first stars."\n\nWhat can the telescope do that our eyes cannot?',
  o:['See infrared light through dust','Travel to other planets','Make the stars brighter','Take colour photos'],
  why:'Выбрана способность, о которой в тексте не говорится. Про путешествия и цветные снимки там ничего нет.',
  rule:'Когда вопрос построен на сравнении — что умеет один и не умеет другой, — ответ прячется рядом со словами cannot, unlike, but. Найди в тексте место, где называется отличие, и читай оттуда. Здесь прямо сказано: телескоп видит инфракрасный свет, который глаз поймать не может, и потому смотрит сквозь пыль.',
  ex:'«It sees infrared — a kind of light our eyes cannot catch»\nСлово cannot указывает на отличие\n«This lets it look through clouds of dust» — следствие этого отличия',
  again:'Отличие ищи там, где стоит отрицание. Оно и отделяет одно от другого.',
  up:{q:'Могут ли наши глаза поймать инфракрасный свет? (yes / no)', a:'no'}}
]
});
